'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { BUILD_ID, BUILD_STAGE, CANDIDATE_FINGERPRINT } = require('../src/core/build-identity');
const { computeCandidateFingerprint } = require('./candidate-identity');
const { PACKAGE_FILES, listFiles } = require('./package-inventory');
const { canonicalFileBytes } = require('./canonical-text');

const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');
const entries = [
  ['src/extension/background-entry.js', 'background.js'],
  ['src/page/entry.js', 'companion-app.js'],
  ['src/content/presentation-bootstrap.js', 'presentation-bootstrap.js'],
  ['src/content/controller.js', 'content-controller.js'],
  ['src/popup/popup.js', 'popup.js']
];

function gitOutput(args, description) {
  try { return execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore','pipe','ignore'] }).trim(); }
  catch (error) { throw new Error(`Unable to ${description}: ${error.message}`); }
}

function sourceIdentity() {
  const sourceSha=gitOutput(['rev-parse','HEAD'],'resolve the authoritative Git HEAD').toLowerCase();
  if(!/^[0-9a-f]{40}$/.test(sourceSha)) throw new Error('A concrete 40-character Git source SHA is required');
  for(const [name,rawValue] of [['GITHUB_SHA',process.env.GITHUB_SHA],['SC_BUILD_SOURCE_SHA',process.env.SC_BUILD_SOURCE_SHA]]) {
    const expectedSha=String(rawValue||'').trim().toLowerCase();
    if(!expectedSha) continue;
    if(!/^[0-9a-f]{40}$/.test(expectedSha)) throw new Error(`${name} must be a concrete 40-character Git SHA`);
    if(expectedSha!==sourceSha) throw new Error(`${name} ${expectedSha} does not match authoritative Git HEAD ${sourceSha}`);
  }
  const sourceDirty=gitOutput(['status','--porcelain','--untracked-files=all','--','.',
    ':(top).github/workflows/squarecoil-extension-validate.yml'],'inspect bounded release-source dirtiness').length>0;
  return {sourceSha,sourceDirty};
}

function slash(value){return value.split(path.sep).join('/');}
function resolveDependency(fromId,request){let resolved=path.posix.normalize(path.posix.join(path.posix.dirname(fromId),request));if(!path.posix.extname(resolved))resolved+='.js';return resolved;}
function bundle(entryId){
  const modules=new Map();const deps=Object.create(null);
  function visit(id){if(modules.has(id))return;const full=path.join(root,...id.split('/'));const source=canonicalFileBytes(full).toString('utf8');modules.set(id,source);deps[id]=Object.create(null);const requirePattern=/require\(\s*(['"])([^'"]+)\1\s*\)/g;let match;while((match=requirePattern.exec(source))){const request=match[2];if(!request.startsWith('.'))throw new Error(`Only relative requires are supported in browser bundles: ${id} -> ${request}`);const resolved=resolveDependency(id,request);deps[id][request]=resolved;visit(resolved);}}
  visit(entryId);
  const moduleSource=[...modules.entries()].map(([id,source])=>`${JSON.stringify(id)}: function(module, exports, require) {\n${source}\n}`).join(',\n');
  return `/* Generated by scripts/build.js. Do not edit dist files directly. */\n`+`(function(){\n'use strict';\n`+`const __modules = {\n${moduleSource}\n};\n`+`const __deps = ${JSON.stringify(deps,null,2)};\n`+`const __cache = Object.create(null);\n`+`function __require(id){\n`+`  if (__cache[id]) return __cache[id].exports;\n`+`  const factory = __modules[id];\n`+`  if (!factory) throw new Error('Missing bundled module: ' + id);\n`+`  const module = { exports: {} };\n`+`  __cache[id] = module;\n`+`  const localRequire = request => {\n`+`    const resolved = (__deps[id] || {})[request];\n`+`    if (!resolved) throw new Error('Unresolved dependency: ' + id + ' -> ' + request);\n`+`    return __require(resolved);\n`+`  };\n`+`  factory(module, module.exports, localRequire);\n`+`  return module.exports;\n`+`}\n`+`__require(${JSON.stringify(entryId)});\n`+`})();\n`;
}

const identity=sourceIdentity();
const candidateFingerprint=computeCandidateFingerprint(root);
if(!/^[0-9a-f]{64}$/.test(candidateFingerprint)) throw new Error('Candidate fingerprint must be a concrete SHA-256');
fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});
for(const [input,output] of entries){let code=bundle(slash(input));if(output==='content-controller.js'){code+='\n/* Proto Squirel Coil nested workspace, isolated-world only. */\n';code+=bundle('src/ui/entry.js');}code=code.split(CANDIDATE_FINGERPRINT).join(candidateFingerprint);if(code.includes(CANDIDATE_FINGERPRINT))throw new Error(`Candidate fingerprint placeholder remained in dist/${output}`);fs.writeFileSync(path.join(dist,output),code,'utf8');console.log(`Built dist/${output}`);}
const themeDist=path.join(dist,'themes');fs.mkdirSync(themeDist,{recursive:true});
for(const name of ['dark-glass.css','light-glass.css']){
  fs.writeFileSync(path.join(themeDist,name),canonicalFileBytes(path.join(root,'src','presentation','ports',name)));
  console.log(`Copied dist/themes/${name}`);
}
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
fs.writeFileSync(path.join(dist,'build-info.json'),JSON.stringify({packageVersion:manifest.version,buildId:BUILD_ID,stage:BUILD_STAGE,candidateFingerprint,sourceSha:identity.sourceSha,sourceDirty:identity.sourceDirty},null,2)+'\n');
const expectedDist=PACKAGE_FILES.filter(relative=>relative.startsWith('dist/')).map(relative=>relative.slice(5)).sort();
const actualDist=listFiles(dist);
if(JSON.stringify(actualDist)!==JSON.stringify(expectedDist))throw new Error(`Canonical dist inventory mismatch. Actual: ${actualDist.join(', ')}`);
