'use strict';

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');
const entries = [
  ['src/extension/background-entry.js', 'background.js'],
  ['src/page/entry.js', 'companion-app.js'],
  ['src/content/controller.js', 'content-controller.js'],
  ['src/popup/popup.js', 'popup.js']
];

function slash(value) {
  return value.split(path.sep).join('/');
}

function resolveDependency(fromId, request) {
  let resolved = path.posix.normalize(path.posix.join(path.posix.dirname(fromId), request));
  if (!path.posix.extname(resolved)) resolved += '.js';
  return resolved;
}

function bundle(entryId) {
  const modules = new Map();
  const deps = Object.create(null);

  function visit(id) {
    if (modules.has(id)) return;
    const full = path.join(root, ...id.split('/'));
    const source = fs.readFileSync(full, 'utf8');
    modules.set(id, source);
    deps[id] = Object.create(null);

    const requirePattern = /require\(\s*(['"])([^'"]+)\1\s*\)/g;
    let match;
    while ((match = requirePattern.exec(source))) {
      const request = match[2];
      if (!request.startsWith('.')) {
        throw new Error(`Only relative requires are supported in browser bundles: ${id} -> ${request}`);
      }
      const resolved = resolveDependency(id, request);
      deps[id][request] = resolved;
      visit(resolved);
    }
  }

  visit(entryId);

  const moduleSource = [...modules.entries()].map(([id, source]) => {
    return `${JSON.stringify(id)}: function(module, exports, require) {\n${source}\n}`;
  }).join(',\n');

  return `/* Generated by scripts/build.js. Do not edit dist files directly. */\n` +
    `(function(){\n'use strict';\n` +
    `const __modules = {\n${moduleSource}\n};\n` +
    `const __deps = ${JSON.stringify(deps, null, 2)};\n` +
    `const __cache = Object.create(null);\n` +
    `function __require(id){\n` +
    `  if (__cache[id]) return __cache[id].exports;\n` +
    `  const factory = __modules[id];\n` +
    `  if (!factory) throw new Error('Missing bundled module: ' + id);\n` +
    `  const module = { exports: {} };\n` +
    `  __cache[id] = module;\n` +
    `  const localRequire = request => {\n` +
    `    const resolved = (__deps[id] || {})[request];\n` +
    `    if (!resolved) throw new Error('Unresolved dependency: ' + id + ' -> ' + request);\n` +
    `    return __require(resolved);\n` +
    `  };\n` +
    `  factory(module, module.exports, localRequire);\n` +
    `  return module.exports;\n` +
    `}\n` +
    `__require(${JSON.stringify(entryId)});\n` +
    `})();\n`;
}

fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });

for (const [input, output] of entries) {
  const code = bundle(slash(input));
  fs.writeFileSync(path.join(dist, output), code, 'utf8');
  console.log(`Built dist/${output}`);
}

const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
fs.writeFileSync(path.join(dist, 'build-info.json'), JSON.stringify({
  packageVersion: manifest.version,
  buildId: 'rebuild-b1-shell-lifecycle',
  stage: 'B1'
}, null, 2) + '\n');
