'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const {createEmptyDocument}=require('../../src/data/model');
const {splitInterval}=require('../../src/data/ledger');
const {createTimerReadModel}=require('../../src/timer/read-model');
function addContext(document,projectId,lastSeenAtMs){const contextId=`job:${projectId}`;document.contexts[contextId]={contextId,kind:'job',projectId:String(projectId),currentLabel:`${projectId} - Prototype`,shortLabel:String(projectId),aliases:[],createdAtMs:1,lastSeenAtMs,workspaceMembership:'RECENT',archivedAtMs:null,legacyUnattributedMs:0};return contextId;}

test('UT-B2-READ-007 workspace rows derive Today, Total, status, and activity from one validated revision',()=>{const atMs=Date.parse('2026-08-27T15:00:00Z');const document=createEmptyDocument({nowMs:atMs,workdayZone:'UTC'});const activeId=addContext(document,'260701',atMs-500);const oldId=addContext(document,'260702',atMs-5_000);document.ledger.push(...splitInterval({sessionId:'old-session',cycleId:'old-cycle',contextId:oldId,startAtMs:atMs-20_000,endAtMs:atMs-10_000,workdayZone:'UTC',createdAtMs:atMs-10_000}));document.timer.active={contextId:activeId,sessionId:'live-session',cycleId:'live-cycle',startedAtMs:atMs-5_000,lastVerifiedAtMs:atMs-1_000,source:'fixture',certainty:'VERIFIED_SERVER',accrualOwnerToken:'owner',startCause:'new-context',safetyHold:null,provisionalSinceMs:null};document.timer.lastObservation={type:'CONTEXT_VERIFIED',contextId:activeId,observedAtMs:atMs-1_000};const value=createTimerReadModel(()=>document,{now:()=>atMs}).snapshot();assert.equal(value.queryAtMs,atMs);assert.equal(value.contextRows.length,2);assert.equal(value.contextRows[0].contextId,activeId);assert.equal(value.contextRows[0].status,'RUNNING');assert.equal(value.contextRows[0].todayMs,5_000);assert.equal(value.contextRows.find(row=>row.contextId===oldId).totalMs,10_000);assert.equal(value.todayByContext.reduce((sum,row)=>sum+row.durationMs,0),15_000);});

test('UT-B2-READ-008 history rows remain ledger-backed, newest-first, and bounded by the requested limit',()=>{const atMs=Date.parse('2026-08-27T15:00:00Z');const document=createEmptyDocument({nowMs:atMs,workdayZone:'UTC'});const contextId=addContext(document,'260703',atMs);for(let index=0;index<3;index+=1){document.ledger.push(...splitInterval({sessionId:`session-${index}`,cycleId:`cycle-${index}`,contextId,startAtMs:atMs-(40_000-index*10_000),endAtMs:atMs-(35_000-index*10_000),workdayZone:'UTC',createdAtMs:atMs-(35_000-index*10_000)}));}const value=createTimerReadModel(()=>document,{now:()=>atMs}).snapshot({historyLimit:2});assert.equal(value.historyRows.length,2);assert.ok(value.historyRows[0].endAtMs>value.historyRows[1].endAtMs);assert.equal(value.historyRows.every(row=>row.contextId===contextId),true);});
