'use strict';

const TIMER_COMMANDS = Object.freeze({
  ACCEPT_OBSERVATION: 'TIMER_ACCEPT_OBSERVATION',
  RESUME: 'TIMER_RESUME',
  START_FRESH: 'TIMER_START_FRESH',
  LOCAL_PAUSE: 'TIMER_LOCAL_PAUSE',
  LOCAL_RESUME: 'TIMER_LOCAL_RESUME',
  COMPANION_DISABLE: 'TIMER_COMPANION_DISABLE',
  RECONCILE_OWNERSHIP: 'TIMER_RECONCILE_OWNERSHIP',
  CONTROLLED_TEARDOWN: 'TIMER_CONTROLLED_TEARDOWN',
  RECOVER_INTERRUPTION: 'TIMER_RECOVER_INTERRUPTION'
});

module.exports = { TIMER_COMMANDS };
