from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "tampermonkey" / "ChatGPT-US-Sign-Glass-Theme.user.js"
text = TARGET.read_text(encoding="utf-8")

if "@version      2.0.3" not in text:
    raise SystemExit("expected canonical ChatGPT Glass Theme v2.0.3")

text = text.replace("@version      2.0.3", "@version      2.0.4", 1)
text = text.replace(
    "US Sign-inspired ChatGPT theme with rotating Bing UHD wallpaper, optimized parallax, truly translucent sidebar glass, a dedicated frosted center reading rail, brighter menus, and a cutout geometric cursor.",
    "US Sign-inspired ChatGPT theme with rotating Bing UHD wallpaper, optimized parallax, translucent sidebar glass, a correctly layered frosted reading rail, brighter menus, and a cutout geometric cursor.",
    1,
)
text = text.replace("window.__chatgptUsSignGlassThemeV203", "window.__chatgptUsSignGlassThemeV204")

old_glass = '''    #us-chatgpt-center-glass {\n      position: fixed !important;\n      top: 48px !important;\n      bottom: 0 !important;\n      left: calc(var(--us-chat-sidebar-edge, 0px) + ((100vw - var(--us-chat-sidebar-edge, 0px)) / 2)) !important;\n      width: min(860px, calc(100vw - var(--us-chat-sidebar-edge, 0px) - 52px)) !important;\n      transform: translateX(-50%) !important;\n      pointer-events: none !important;\n      z-index: 1 !important;\n      background: rgba(10, 21, 32, 0.30) !important;\n      background-image: linear-gradient(180deg, rgba(183, 220, 249, 0.042), rgba(255,255,255,0.010)) !important;\n      border-left: 1px solid rgba(195, 225, 249, 0.075) !important;\n      border-right: 1px solid rgba(195, 225, 249, 0.075) !important;\n      box-shadow: 0 0 60px rgba(0,0,0,0.10), inset 0 1px 0 rgba(255,255,255,0.028) !important;\n      -webkit-backdrop-filter: blur(22px) saturate(124%) !important;\n      backdrop-filter: blur(22px) saturate(124%) !important;\n    }\n\n    body {\n      z-index: auto !important;\n    }\n\n    body > #__next,\n    body > #root {\n      position: relative !important;\n      z-index: 2 !important;\n    }'''
new_glass = '''    /* v2.0.4: put the frost inside ChatGPT's main stacking context and\n       behind the actual conversation. The wallpaper is blurred; text is not. */\n    main,\n    [role="main"] {\n      position: relative !important;\n      isolation: isolate !important;\n    }\n\n    main::before,\n    [role="main"]:not(main)::before {\n      content: "" !important;\n      position: fixed !important;\n      top: 48px !important;\n      bottom: 0 !important;\n      left: calc(var(--us-chat-sidebar-edge, 0px) + ((100vw - var(--us-chat-sidebar-edge, 0px)) / 2)) !important;\n      width: min(860px, calc(100vw - var(--us-chat-sidebar-edge, 0px) - 52px)) !important;\n      transform: translateX(-50%) !important;\n      pointer-events: none !important;\n      z-index: -1 !important;\n      background: rgba(10, 21, 32, 0.30) !important;\n      background-image: linear-gradient(180deg, rgba(183, 220, 249, 0.042), rgba(255,255,255,0.010)) !important;\n      border-left: 1px solid rgba(195, 225, 249, 0.075) !important;\n      border-right: 1px solid rgba(195, 225, 249, 0.075) !important;\n      box-shadow: 0 0 60px rgba(0,0,0,0.10), inset 0 1px 0 rgba(255,255,255,0.028) !important;\n      -webkit-backdrop-filter: blur(22px) saturate(124%) !important;\n      backdrop-filter: blur(22px) saturate(124%) !important;\n    }'''
if old_glass not in text:
    raise SystemExit("v2.0.3 center glass block anchor not found")
text = text.replace(old_glass, new_glass, 1)

old_runtime = '''  /* v2.0.3 dedicated center glass rail. Keeping this as a stable theme-owned\n     layer avoids relying on ChatGPT's frequently changing conversation wrappers. */\n  function mountCenterGlassRail() {\n    if (!document.body) return false;\n    let rail = document.getElementById("us-chatgpt-center-glass");\n    if (!rail) {\n      rail = document.createElement("div");\n      rail.id = "us-chatgpt-center-glass";\n      rail.setAttribute("aria-hidden", "true");\n      document.body.prepend(rail);\n    }\n\n    const updateSidebarEdge = () => {\n      const candidates = Array.from(document.querySelectorAll(\n        'aside, [data-testid="left-sidebar"], [data-testid="sidebar"], [data-testid="navigation-sidebar"], nav'\n      ));\n      const sidebar = candidates\n        .map((node) => ({ node, rect: node.getBoundingClientRect() }))\n        .filter(({ rect }) => rect.width >= 170 && rect.width <= 420 && rect.height >= window.innerHeight * 0.55 && rect.left <= 8)\n        .sort((a, b) => b.rect.height - a.rect.height)[0];\n      const edge = sidebar ? Math.max(0, Math.round(sidebar.rect.right)) : 0;\n      document.documentElement.style.setProperty("--us-chat-sidebar-edge", `${edge}px`);\n      return sidebar?.node || null;\n    };\n\n    const sidebarNode = updateSidebarEdge();\n    window.addEventListener("resize", updateSidebarEdge, { passive: true });\n    if (sidebarNode && typeof ResizeObserver === "function") {\n      const ro = new ResizeObserver(updateSidebarEdge);\n      ro.observe(sidebarNode);\n    }\n    return true;\n  }\n\n  if (!mountCenterGlassRail()) {\n    window.addEventListener("DOMContentLoaded", mountCenterGlassRail, { once: true });\n  }'''
new_runtime = '''  /* v2.0.4 center rail geometry only. The visual frost is owned by\n     main::before so it always stays behind ChatGPT's conversation content. */\n  function initCenterGlassRailGeometry() {\n    const updateSidebarEdge = () => {\n      const candidates = Array.from(document.querySelectorAll(\n        'aside, [data-testid="left-sidebar"], [data-testid="sidebar"], [data-testid="navigation-sidebar"], nav'\n      ));\n      const sidebar = candidates\n        .map((node) => ({ node, rect: node.getBoundingClientRect() }))\n        .filter(({ rect }) => rect.width >= 170 && rect.width <= 420 && rect.height >= window.innerHeight * 0.55 && rect.left <= 8)\n        .sort((a, b) => b.rect.height - a.rect.height)[0];\n      const edge = sidebar ? Math.max(0, Math.round(sidebar.rect.right)) : 0;\n      document.documentElement.style.setProperty("--us-chat-sidebar-edge", `${edge}px`);\n      return sidebar?.node || null;\n    };\n\n    const sidebarNode = updateSidebarEdge();\n    window.addEventListener("resize", updateSidebarEdge, { passive: true });\n    if (sidebarNode && typeof ResizeObserver === "function") {\n      const ro = new ResizeObserver(updateSidebarEdge);\n      ro.observe(sidebarNode);\n    }\n  }\n\n  if (document.readyState === "loading") {\n    window.addEventListener("DOMContentLoaded", initCenterGlassRailGeometry, { once: true });\n  } else {\n    initCenterGlassRailGeometry();\n  }'''
if old_runtime not in text:
    raise SystemExit("v2.0.3 center rail runtime anchor not found")
text = text.replace(old_runtime, new_runtime, 1)

TARGET.write_text(text, encoding="utf-8")
