from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "tampermonkey" / "ChatGPT-US-Sign-Glass-Theme.user.js"
text = TARGET.read_text(encoding="utf-8")

if "@version      2.0.11" not in text:
    raise SystemExit("expected canonical ChatGPT Glass Theme v2.0.11")

text = text.replace("@version      2.0.11", "@version      2.0.12", 1)
text = text.replace(
    "US Sign-inspired ChatGPT theme with resilient 30-minute Bing UHD rotation, optimized parallax, translucent sidebar glass, runtime-marked native reading glass, native document stacking, brighter menus, and a cutout geometric cursor.",
    "US Sign-inspired ChatGPT theme with resilient 30-minute Bing UHD rotation, optimized parallax, translucent sidebar glass, DOM-grounded thread reading glass, native document stacking, brighter menus, and a cutout geometric cursor.",
    1,
)
text = text.replace("window.__chatgptUsSignGlassThemeV211", "window.__chatgptUsSignGlassThemeV212")

old_glass = '''    /* v2.0.11: visible rear reading glass on ChatGPT's native message rail.\n       The runtime marker below finds the real rendered message column when\n       ChatGPT changes test IDs, without changing width, positioning, or z-index. */\n    main {\n      background: transparent !important;\n      background-image: none !important;\n      -webkit-backdrop-filter: none !important;\n      backdrop-filter: none !important;\n    }\n\n    [data-testid="conversation-turn-list"],\n    .us-sign-chat-reading-rail {\n      background: rgba(12, 25, 38, 0.38) !important;\n      background-image: linear-gradient(180deg, rgba(190, 224, 250, 0.060), rgba(255,255,255,0.014)) !important;\n      border: 1px solid rgba(195, 225, 249, 0.115) !important;\n      border-radius: 24px !important;\n      box-shadow: 0 18px 64px rgba(0,0,0,0.16), inset 0 1px 0 rgba(255,255,255,0.040) !important;\n      -webkit-backdrop-filter: blur(22px) saturate(126%) !important;\n      backdrop-filter: blur(22px) saturate(126%) !important;\n    }'''

new_glass = '''    /* v2.0.12: DOM-grounded rear reading glass. The live ChatGPT build\n       exposes full-width turn sections with a 768px centered message column.\n       Mark the shared thread wrapper and paint one centered rail behind all\n       turns. No fixed viewport overlay and no header/main positioning changes. */\n    main {\n      background: transparent !important;\n      background-image: none !important;\n      -webkit-backdrop-filter: none !important;\n      backdrop-filter: none !important;\n    }\n\n    [data-testid="conversation-turn-list"] {\n      background: transparent !important;\n      border: 0 !important;\n      box-shadow: none !important;\n      -webkit-backdrop-filter: none !important;\n      backdrop-filter: none !important;\n    }\n\n    .us-sign-chat-thread-root {\n      position: relative !important;\n      background: transparent !important;\n      background-image: none !important;\n    }\n\n    .us-sign-chat-thread-root::before {\n      content: "" !important;\n      position: absolute !important;\n      top: 0 !important;\n      bottom: 0 !important;\n      left: 50% !important;\n      width: min(920px, calc(100% - 56px)) !important;\n      transform: translateX(-50%) !important;\n      pointer-events: none !important;\n      z-index: 0 !important;\n      background: rgba(12, 25, 38, 0.42) !important;\n      background-image: linear-gradient(180deg, rgba(190, 224, 250, 0.070), rgba(255,255,255,0.016)) !important;\n      border-left: 1px solid rgba(195, 225, 249, 0.13) !important;\n      border-right: 1px solid rgba(195, 225, 249, 0.13) !important;\n      box-shadow: 0 0 68px rgba(0,0,0,0.17), inset 0 1px 0 rgba(255,255,255,0.045) !important;\n      -webkit-backdrop-filter: blur(18px) saturate(124%) !important;\n      backdrop-filter: blur(18px) saturate(124%) !important;\n    }\n\n    .us-sign-chat-thread-root > * {\n      position: relative !important;\n      z-index: 1 !important;\n    }'''

if old_glass not in text:
    raise SystemExit("v2.0.11 reading glass block not found")
text = text.replace(old_glass, new_glass, 1)

start = text.find('  /* v2.0.11: mark the real native reading rail without owning geometry. */')
end = text.find('  const PARALLAX_X = 5;', start)
if start == -1 or end == -1:
    raise SystemExit("v2.0.11 reading rail runtime block not found")

new_runtime = '''  /* v2.0.12: use the real full-width turn sections to find their shared\n     thread wrapper, then mark only that wrapper for the center glass rail. */\n  let threadRailObserver = null;\n  let threadRailStopTimer = 0;\n  let threadRailRaf = 0;\n\n  function findThreadRoot() {\n    const main = document.querySelector("main");\n    if (!main) return null;\n\n    const turns = Array.from(main.querySelectorAll('section[data-testid^="conversation-turn-"]'));\n    if (!turns.length) return null;\n\n    const first = turns[0];\n    const last = turns[turns.length - 1];\n    let common = first;\n    while (common && common !== main && !common.contains(last)) common = common.parentElement;\n    if (!common || common === main) return null;\n\n    return common;\n  }\n\n  function markThreadRoot() {\n    const target = findThreadRoot();\n    if (!target) return false;\n    document.querySelectorAll(".us-sign-chat-thread-root").forEach((node) => {\n      if (node !== target) node.classList.remove("us-sign-chat-thread-root");\n    });\n    target.classList.add("us-sign-chat-thread-root");\n    return true;\n  }\n\n  function scheduleThreadRootMark() {\n    if (threadRailRaf) return;\n    threadRailRaf = window.requestAnimationFrame(() => {\n      threadRailRaf = 0;\n      markThreadRoot();\n    });\n  }\n\n  function startThreadRailDiscovery() {\n    if (threadRailObserver) threadRailObserver.disconnect();\n    if (threadRailStopTimer) window.clearTimeout(threadRailStopTimer);\n    markThreadRoot();\n\n    const root = document.querySelector("main");\n    if (!root || typeof MutationObserver !== "function") return;\n    threadRailObserver = new MutationObserver(scheduleThreadRootMark);\n    threadRailObserver.observe(root, { childList: true, subtree: true });\n    threadRailStopTimer = window.setTimeout(() => {\n      threadRailObserver?.disconnect();\n      threadRailObserver = null;\n      threadRailStopTimer = 0;\n      markThreadRoot();\n    }, 12000);\n  }\n\n  function queueThreadRailDiscovery() {\n    window.setTimeout(startThreadRailDiscovery, 0);\n    window.setTimeout(markThreadRoot, 350);\n    window.setTimeout(markThreadRoot, 1200);\n  }\n\n  const nativePushState = history.pushState;\n  history.pushState = function (...args) {\n    const result = nativePushState.apply(this, args);\n    queueThreadRailDiscovery();\n    return result;\n  };\n  const nativeReplaceState = history.replaceState;\n  history.replaceState = function (...args) {\n    const result = nativeReplaceState.apply(this, args);\n    queueThreadRailDiscovery();\n    return result;\n  };\n  window.addEventListener("popstate", queueThreadRailDiscovery, { passive: true });\n  window.addEventListener("pageshow", queueThreadRailDiscovery, { passive: true });\n\n  if (document.readyState === "loading") {\n    window.addEventListener("DOMContentLoaded", queueThreadRailDiscovery, { once: true });\n  } else {\n    queueThreadRailDiscovery();\n  }\n\n'''

text = text[:start] + new_runtime + text[end:]
TARGET.write_text(text, encoding="utf-8")
